name: Build and Deploy Package Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GitHub Pages
      uses: actions/configure-pages@v3

    - name: Build and Prepare Package Repo
      run: |
        # Ensure the output directory exists
        mkdir -p output

        # Copy valid package files and their version files to the output directory
        for file in *; do
          if [[ -f "$file" && -f "$file.ver" ]]; then
            cp "$file" "$file.ver" output/
          fi
        done

        # Confirm files were copied
        echo "Files prepared for deployment:"
        ls -l output

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: output

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
